# Spring Settings
spring.application.name=flowset-operaton-demo

spring.datasource.url=jdbc:h2:file:./h2/operaton-h2-database
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

server.port=8080

# Operaton Settings
operaton.bpm.admin-user.id=admin
operaton.bpm.admin-user.password=admin

operaton.bpm.auto-deployment-enabled=true
operaton.bpm.deployment-resource-pattern=classpath*:**/*.bpmn, classpath*:**/*.form,  classpath*:**/*.dmn, classpath*:**/*.cmmn

operaton.bpm.generic-properties.properties.historyTimeToLive=180

ai.openai.api-url=https://api.openai.com/v1/chat/completions
ai.openai.model=gpt-4o-mini
ai.openai.timeout-seconds=15
ai.openai.api-key=<api-key>